---

- name: Set timezone
  file:
    src: /usr/share/zoneinfo/Europe/London
    dest: /etc/localtime
    state: link
    force: yes

- name: Install chrony
  apt:
    name: chrony
    state: present
    update_cache: yes

- name: Enable chrony daemon
  service:
    name: chrony
    enabled: yes

- name: Start chrony daemon
  service:
    name: chrony
    state: started
