---

collections:
  - name: community.general
    version: 5.0.1
  - name: ansible.posix
    version: 1.4.0
roles:
  - name: geerlingguy.nodejs
    version: 6.0.0
  - name: geerlingguy.postgresql
    version: 3.3.0
  - name: geerlingguy.redis
    version: 1.7.0
  - name: nginxinc.nginx
    version: 0.23.1
  - name: zzet.rbenv
    version: 3.6.0