---

collections:
  - name: community.general
    version: 3.2.0
  - name: ansible.posix
    version: 1.2.0
  - name: community.postgresql
    version: 1.3.0
  - name: nginxinc.nginx_core
    version: 0.3.0
