---

- name: Enable ufw and deny everything
  community.general.ufw:
    state: enabled
    policy: "deny"
    logging: "on"

- name: Enable ports
  community.general.ufw:
    rule: "allow"
    port: "{{ item }}"
    proto: "tcp"
  with_items:
    - "80"
    - "443"

- name: Rate limit for SSH
  community.general.ufw:
    rule: "limit"
    port: "22"
    proto: "tcp"

- name: Start firewall
  service:
    name: "ufw"
    state: "started"